repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
        files: ^((custom_components|tests)/.+)?[^/]+\.py$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args:
          - --toml
          - pyproject.toml
          - --quiet-level=2
        exclude_types: [csv, json]
        exclude: ^tests/fixtures/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=main

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2
          - prettier-plugin-sort-json@4.2.0

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: script/run-in-env.sh mypy
        language: script
        require_serial: true
        files: ^custom_components/isy994/.*\.py$
      - id: pylint
        name: pylint
        entry: script/run-in-env.sh pylint --rcfile=.pylintrc
        language: script
        require_serial: true
        files: ^custom_components/isy994/.*\.py$
