[mypy]
# Allow missing imports for the development environment where pyisyox
# may not be installed in the same environment when running pre-commit.
ignore_missing_imports = True
follow_imports = skip
