name: CI

"on":
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v5

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  lint:
    runs-on: ubuntu-latest
    name: Check code style
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch,mypy,pylint
